INSERT INTO director (director_name)
VALUES
    ("Christopher Nolan"),
    ("Steven Spielberg"),
    ("Martin Scorsese"),
    ("James Cameron"),
    ("Quentin Tarantino"),
    ("Ridley Scott"),
    ("Peter Jackson"),
    ("Denis Villeneuve"),
    ("David Fincher"),
    ("Guillermo del Toro"),
    ("Alfonso Cuarón"),
    ("Bong Joon-ho"),
    ("Guy Ritchie"),
    ("Tim Burton"),
    ("Patty Jenkins"),
    ("Greta Gerwig"),
    ("Francis Ford Coppola"),
    ("George Lucas"),
    ("Clint Eastwood"),
    ("Zack Snyder"),
    ("Lana Wachowski"),
    ("Anthony Russo"),
    ("Damien Chazelle"),
    ("Todd Phillips"),
    ("Frank Darabont"),
    ("Jon Favreau"),
    ("Chris Columbus");

INSERT INTO actor (actor_name, actor_photo)
VALUES
    ("Leonardo DiCaprio", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Leonardo_Dicaprio_-_World_Premiere_‘One_Battle_after_Another’.jpg/250px-Leonardo_Dicaprio_-_World_Premiere_‘One_Battle_after_Another’.jpg"),
    ("Morgan Freeman", "https://m.media-amazon.com/images/M/MV5BMTc0MDMyMzI2OF5BMl5BanBnXkFtZTcwMzM2OTk1MQ@@._V1_.jpg"),
    ("Scarlett Johansson", "https://m.media-amazon.com/images/M/MV5BMTM3OTUwMDYwNl5BMl5BanBnXkFtZTcwNTUyNzc3Nw@@._V1_.jpg"),
    ("Tom Hanks", "https://m.media-amazon.com/images/M/MV5BMTQ2MjMwNDA3Nl5BMl5BanBnXkFtZTcwMTA2NDY3NQ@@._V1_FMjpg_UX1000_.jpg"),
    ("Natalie Portman", "https://m.media-amazon.com/images/M/MV5BNjk1M2RmODAtMjE0Ny00N2U0LWIwNWYtZTAxMDFiMzk1MjU5XkEyXkFqcGc@._V1_.jpg"),
    ("Christian Bale", "https://m.media-amazon.com/images/M/MV5BMTkxMzk4MjQ4MF5BMl5BanBnXkFtZTcwMzExODQxOA@@._V1_.jpg"),
    ("Robert Downey Jr.", "https://m.media-amazon.com/images/M/MV5BNzg1MTUyNDYxOF5BMl5BanBnXkFtZTgwNTQ4MTE2MjE@._V1_FMjpg_UX1000_.jpg"),
    ("Emma Stone", "https://m.media-amazon.com/images/M/MV5BMjI4NjM1NDkyN15BMl5BanBnXkFtZTgwODgyNTY1MjE@._V1_.jpg"),
    ("Brad Pitt", "https://m.media-amazon.com/images/M/MV5BZTlhMWIxZjAtMWQ5YS00YmU0LTkwN2QtN2M5ZDRjYmRkMWFlXkEyXkFqcGc@._V1_.jpg"),
    ("Anne Hathaway", "https://br.web.img2.acsta.net/pictures/19/10/16/01/22/0121805.jpg"),
    ("Keanu Reeves", "https://m.media-amazon.com/images/M/MV5BNDEzOTdhNDUtY2EyMy00YTNmLWE5MjItZmRjMmQzYTRlMGRkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Jennifer Lawrence", "https://m.media-amazon.com/images/M/MV5BOTU3NDE5MDQ4MV5BMl5BanBnXkFtZTgwMzE5ODQ3MDI@._V1_FMjpg_UX1000_.jpg"),
    ("Johnny Depp", "https://m.media-amazon.com/images/M/MV5BZjA3NzZiZDktZjc2My00MzY2LThhOWMtZGFjYzg4ZDI2ZWVmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Matt Damon", "https://m.media-amazon.com/images/M/MV5BMTM0NzYzNDgxMl5BMl5BanBnXkFtZTcwMDg2MTMyMw@@._V1_.jpg"),
    ("Amy Adams", "https://m.media-amazon.com/images/M/MV5BMTg2NTk2MTgxMV5BMl5BanBnXkFtZTgwNjcxMjAzMTI@._V1_FMjpg_UX1000_.jpg"),
    ("Denzel Washington", "https://m.media-amazon.com/images/M/MV5BMjExMjY5ODYyM15BMl5BanBnXkFtZTgwOTU0OTg0NDM@._V1_.jpg"),
    ("Chris Evans", "https://m.media-amazon.com/images/M/MV5BNzQ0YWM1ODEtZDFkYy00MGJhLTkwZDUtMzVkZjljODU3ZTRmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Gal Gadot", "https://m.media-amazon.com/images/M/MV5BNWJmNDNiMzgtOGNlOC00MmU4LThkNjUtNTIxNmQwMzQ4NTczXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Henry Cavill", "https://m.media-amazon.com/images/M/MV5BNWFmNmI2NmYtNDUyYi00MDZhLTk0ZmEtODY0MmM5NGQxMWEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Mark Ruffalo", "https://m.media-amazon.com/images/M/MV5BM2JiYzA0ZGItNmFhYy00MjIyLWEwN2QtMzRmNDUyNjNiZjBiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Matthew McConaughey", "https://upload.wikimedia.org/wikipedia/commons/8/8c/Matthew_McConaughey_at_the_2025_Toronto_Film_Festival_%28Cropped%29.jpg"),
    ("Heath Ledger", "https://m.media-amazon.com/images/M/MV5BMTI2NTY0NzA4MF5BMl5BanBnXkFtZTYwMjE1MDE0._V1_FMjpg_UX1000_.jpg"),
    ("Michael Caine", "https://image.tmdb.org/t/p/w500/bVZRMlpjTAO2pJK6v90buFgVbSW.jpg"),
    ("Laurence Fishburne", "https://m.media-amazon.com/images/M/MV5BMTc0NjczNDc1MV5BMl5BanBnXkFtZTYwMDU0Mjg1._V1_FMjpg_UX1000_.jpg"),
    ("Carrie-Anne Moss", "https://m.media-amazon.com/images/M/MV5BMTYxMjgwNzEwOF5BMl5BanBnXkFtZTcwNTQ0NzI5Ng@@._V1_.jpg"),
    ("Chris Hemsworth", "https://m.media-amazon.com/images/M/MV5BOTU2MTI0NTIyNV5BMl5BanBnXkFtZTcwMTA4Nzc3OA@@._V1_FMjpg_UX1000_.jpg"),
    ("Kate Winslet", "https://m.media-amazon.com/images/M/MV5BODgzMzM2NTE0Ml5BMl5BanBnXkFtZTcwMTcyMTkyOQ@@._V1_FMjpg_UX1000_.jpg"),
    ("Al Pacino", "https://m.media-amazon.com/images/M/MV5BMTQzMzg1ODAyNl5BMl5BanBnXkFtZTYwMjAxODQ1._V1_FMjpg_UX1000_.jpg"),
    ("Marlon Brando", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Marlon_Brando_publicity_for_One-Eyed_Jacks.png/960px-Marlon_Brando_publicity_for_One-Eyed_Jacks.png"),
    ("John Travolta", "https://m.media-amazon.com/images/M/MV5BNWUyNDZiMjItMjQzMy00YmQyLTliOTYtOGRkYzNhZTk5NDBiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Samuel L. Jackson", "https://m.media-amazon.com/images/M/MV5BMTQ1NTQwMTYxNl5BMl5BanBnXkFtZTYwMjA1MzY1._V1_FMjpg_UX1000_.jpg"),
    ("Uma Thurman", "https://m.media-amazon.com/images/M/MV5BMjMxNzk1MTQyMl5BMl5BanBnXkFtZTgwMDIzMDEyMTE@._V1_.jpg"),
    ("Ryan Gosling", "https://m.media-amazon.com/images/M/MV5BMTQzMjkwNTQ2OF5BMl5BanBnXkFtZTgwNTQ4MTQ4MTE@._V1_FMjpg_UX1000_.jpg"),
    ("Song Kang-ho", "https://m.media-amazon.com/images/M/MV5BYmI2OTQwMmItMDI5OS00OGQxLWIyZGUtNThlNjRjODkwMTI1XkEyXkFqcGc@._V1_.jpg"),
    ("Joaquin Phoenix", "https://m.media-amazon.com/images/M/MV5BYjFjNGYzYjEtNGE0Ny00M2IyLTk5ZmYtODE3ZGFkMzVjYmNmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Robert De Niro", "https://m.media-amazon.com/images/M/MV5BMjAwNDU3MzcyOV5BMl5BanBnXkFtZTcwMjc0MTIxMw@@._V1_FMjpg_UX1000_.jpg"),
    ("Timothée Chalamet", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Timothée_Chalamet-63482_%28cropped%29.jpg"),
    ("Zendaya", "https://br.web.img2.acsta.net/c_310_420/pictures/19/10/15/01/30/2336295.jpg"),
    ("Tim Robbins", "https://m.media-amazon.com/images/M/MV5BMTI1OTYxNzAxOF5BMl5BanBnXkFtZTYwNTE5ODI4._V1_FMjpg_UX1000_.jpg"),
    ("Mark Hamill", "https://m.media-amazon.com/images/M/MV5BMjZjY2I2NmYtMTMxMC00OTYwLWI0M2UtZWNkYzMyOGNlNmY4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Harrison Ford", "https://m.media-amazon.com/images/M/MV5BMTY4Mjg0NjIxOV5BMl5BanBnXkFtZTcwMTM2NTI3MQ@@._V1_FMjpg_UX1000_.jpg"),
    ("Carrie Fisher", "https://br.web.img3.acsta.net/r_1280_720/pictures/18/01/12/12/19/5619073.jpg"),
    ("Chris Pine", "https://upload.wikimedia.org/wikipedia/commons/0/01/Chris_Pine_2%2C_2013.jpg"),
    ("Edward Norton", "https://m.media-amazon.com/images/M/MV5BMTYwNjQ5MTI1NF5BMl5BanBnXkFtZTcwMzU5MTI2Mw@@._V1_FMjpg_UX1000_.jpg"),
    ("Daniel Radcliffe", "https://m.media-amazon.com/images/M/MV5BYzVmYjIxMzgtZWU2Ny00MjAyLTk5ZWUtZDEyMTliYjczMmIxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    ("Emma Watson", "https://m.media-amazon.com/images/M/MV5BMTQ3ODE2NTMxMV5BMl5BanBnXkFtZTgwOTIzOTQzMjE@._V1_.jpg"),
    ("Rupert Grint", "https://m.media-amazon.com/images/M/MV5BODUwOTc5N2MtNTVmZi00MWE0LWE0Y2QtOTAyOTEzZDg1NGFiXkEyXkFqcGc@._V1_.jpg"),
    ("Joseph Gordon-Levitt", "https://m.media-amazon.com/images/M/MV5BMTY3NTk0NDI3Ml5BMl5BanBnXkFtZTgwNDA3NjY0MjE@._V1_.jpg"),
    ("Jessica Chastain", "https://m.media-amazon.com/images/M/MV5BMTU1MDM5NjczOF5BMl5BanBnXkFtZTcwOTY2MDE4OA@@._V1_.jpg");

INSERT INTO genre (genre)
VALUES
    ("Ação"),
    ("Aventura"),
    ("Drama"),
    ("Comédia"),
    ("Suspense"),
    ("Terror"),
    ("Romance"),
    ("Sci-Fi"),
    ("Fantasia"),
    ("Mistério"),
    ("Crime"),
    ("Animação"),
    ("Histórico"),
    ("Guerra"),
    ("Musical"),
    ("Esporte"),
    ("Thriller"),
    ("Documentário");

INSERT INTO movie ( movie_title, duration_time, publication_year, movie_synopsis, movie_poster)
VALUES
    (
        "Inception",
        "02:28:00",
        2010,
        "Um ladrão invade sonhos à procura de segredos corporativos.",
        "https://m.media-amazon.com/images/I/71iDkRVDZNL.jpg"
    ),
    (
        "Interstellar",
        "02:49:00",
        2014,
        "Exploradores viajam através de um buraco de minhoca para salvar a humanidade.",
        "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF894,1000_QL80_.jpg"
    ),
    (
        "The Dark Knight",
        "02:32:00",
        2008,
        "Batman enfrenta o Coringa em Gotham.",
        "https://i.pinimg.com/736x/19/3f/d8/193fd849ee503fb6a773a9fc86209e9b.jpg"
    ),
    (
        "Matrix",
        "02:16:00",
        1999,
        "Um hacker descobre a verdade sobre sua realidade.",
        "https://m.media-amazon.com/images/M/MV5BZGM1NDM3MTAtMmI0ZC00ZDAwLWEwY2EtNDdhYjZmMjJkNzM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
    ),
    (
        "Avengers: Endgame",
        "03:01:00",
        2019,
        "Os Vingadores enfrentam Thanos pela última vez.",
        "https://images.justwatch.com/poster/312869330/s718/vingadores-endgame.jpg"
    ),
    (
        "Titanic",
        "03:14:00",
        1997,
        "Romance entre passageiros do navio mais famoso.",
        "https://m.media-amazon.com/images/I/71GUAV0mfDL._AC_SL1000_.jpg"
    ),
    (
        "O Poderoso Chefão",
        "02:55:00",
        1972,
        "A ascensão da família Corleone.",
        "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg"
    ),
    (
        "Pulp Fiction",
        "02:34:00",
        1994,
        "Histórias interligadas no submundo de Los Angeles.",
        "https://uauposters.com.br/media/catalog/product/0/4/047620140408-posters-filmes-retro-pulp-fiction-tarantino.jpg"
    ),
    (
        "La La Land",
        "02:08:00",
        2016,
        "Um músico e uma aspirante a atriz se apaixonam.",
        "https://www.papodecinema.com.br/wp-content/uploads/2017/01/20190123-la-la-land.webp"
    ),
    (
        "Parasite",
        "02:12:00",
        2019,
        "Famílias colidem em trama de desigualdade social.",
        "https://a.ltrbxd.com/resized/film-poster/4/2/6/4/0/6/426406-parasite-0-230-0-345-crop.jpg?v=8f5653f710"
    ),
    (
        "Perdido em Marte",
        "02:24:00",
        2015,
        "Astronauta tenta sobreviver em Marte.",
        "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10980706_p_v13_ar.jpg"
    ),
    (
        "Coringa",
        "02:02:00",
        2019,
        "A origem do vilão mais famoso de Gotham.",
        "https://resizing.flixster.com/z4hiL8ZBmyZYrgP523AZvdk7uUI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzRmOWU4ODJhLTNkMzAtNDNhMC04YjhjLWVkMjJjMGI4MjE4Ni5wbmc="
    ),
    (
        "Dune",
        "02:35:00",
        2021,
        "Paul Atreides luta pelo controle de Arrakis.",
        "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_.jpg"
    ),
    (
        "O Sonho de Liberdade",
        "02:22:00",
        1994,
        "Prisioneiro busca liberdade e esperança.",
        "https://m.media-amazon.com/images/I/71nBGhNjGIL._AC_UF1000,1000_QL80_.jpg"
    ),
    (
        "Star Wars: Uma nova esperança",
        "02:01:00",
        1977,
        "A resistência enfrenta o império.",
        "https://play-lh.googleusercontent.com/7OTx1DboUIszuMbHZwFHhYOLRQspWozEx7xFtYKG674mtGA_PSRPGIdtv7jmR4jQ9d0"
    ),
    (
        "Mulher Maravilha",
        "02:21:00",
        2017,
        "Diana enfrenta Ares durante a guerra.",
        "https://uauposters.com.br/media/catalog/product/1/1/115220180226-uau-posters-filmes-wonder-woman-mulher-maravilha.jpg"
    ),
    (
        "Blade Runner 2049",
        "02:44:00",
        2017,
        "Um blade runner descobre segredos proibidos.",
        "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg"
    ),
    (
        "Clube da Luta",
        "02:19:00",
        1999,
        "Homens criam um clube secreto.",
        "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
    ),
    (
        "Homem de Ferro",
        "02:06:00",
        2008,
        "Tony Stark cria sua armadura lendária.",
        "https://uauposters.com.br/media/catalog/product/1/6/161320140525-uau-posters-filmes-homem-de-ferro--iron-man--2.jpg"
    ),
    (
        "Harry Potter e a Pedra Filosofal",
        "02:32:00",
        2001,
        "Um garoto descobre que é bruxo.",
        "https://m.media-amazon.com/images/I/715YKSv-XuL.jpg"
    );

INSERT INTO movie_director (id_movie, id_director)
VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 21),
    (5, 22),
    (6, 4),
    (7, 17),
    (8, 5),
    (9, 23),
    (10, 12),
    (11, 6),
    (12, 24),
    (13, 8),
    (14, 25),
    (15, 18),
    (16, 15),
    (17, 8),
    (18, 9),
    (19, 26),
    (20, 27);

INSERT INTO movie_actor (id_movie, id_actor)
VALUES
    (1, 1),
    (1, 48),
    (1, 23),
    (2, 21),
    (2, 10),
    (2, 14),
    (2, 49),
    (3, 6),
    (3, 22),
    (3, 23),
    (4, 11),
    (4, 24),
    (4, 25),
    (5, 7),
    (5, 17),
    (5, 20),
    (5, 26),
    (5, 3),
    (6, 1),
    (6, 27),
    (7, 29),
    (7, 28),
    (8, 30),
    (8, 31),
    (8, 32),
    (9, 8),
    (9, 33),
    (10, 34),
    (11, 14),
    (11, 49),
    (12, 35),
    (12, 36),
    (13, 37),
    (13, 38),
    (14, 39),
    (14, 2),
    (15, 40),
    (15, 41),
    (15, 42),
    (16, 18),
    (16, 43),
    (17, 33),
    (17, 41),
    (18, 9),
    (18, 44),
    (19, 7),
    (20, 45),
    (20, 46),
    (20, 47);

INSERT INTO movie_genre (id_movie, id_genre)
VALUES
    (1, 8),
    (1, 5),
    (2, 8),
    (2, 3),
    (3, 1),
    (3, 11),
    (4, 8),
    (4, 5),
    (5, 1),
    (5, 8),
    (6, 7),
    (6, 3),
    (7, 11),
    (7, 3),
    (8, 11),
    (8, 4),
    (9, 7),
    (9, 16),
    (10, 3),
    (10, 5),
    (11, 2),
    (11, 8),
    (12, 11),
    (12, 3),
    (13, 8),
    (13, 2),
    (14, 3),
    (14, 11),
    (15, 2),
    (15, 9),
    (16, 1),
    (16, 2),
    (17, 8),
    (17, 5),
    (18, 11),
    (18, 3),
    (19, 1),
    (19, 8),
    (20, 9),
    (20, 2);

INSERT INTO user (user, password, user_role, user_name, email, created_at)
VALUES 
    ("Adm", "123456", "Administrador", "Samuel Miller Soares", "administrador@gmail.com", "2025-11-16"),
    ("Comum", "123456", "Comum", "Samuel Miller Soares", "comum@gmail.com", "2025-11-16");

INSERT INTO review (id_movie, id_user, review_text, review_rating, review_date)
VALUES
    (1, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 4.9, "2025-11-10"),
    (1, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 2.0, "2025-11-10"),
    (2, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (3, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (4, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (5, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (6, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (7, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (8, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (9, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (10, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (11, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (12, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (13, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (14, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (15, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (16, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (17, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (18, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (19, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (20, 1, "Comentário de teste para verificar a funcionalidade de avaliações.", 5.0, "2025-11-10"),
    (5, 2, "Comentário de teste para verificar a funcionalidade de avaliações.", 1.0, "2025-11-10");
